index:
  path: /admin
  controller: App\Controller\HomeController::index

homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /admin
    permanent: true

api_login_check:
  path: /api/login_check
